services:
  # Backend Service
  - type: web
    name: blog-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 8080
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"

  # Frontend Service
  - type: static
    name: blog-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://your-backend-url.onrender.com/api
